import {
	Calendar,
	CheckSquare,
	ChevronsUpDown,
	FileText,
	SlidersHorizontal,
	Star,
	TrendingUp,
	Type,
	Upload,
} from "lucide-react";

export const questionTypeIcons: Record<string, React.ElementType> = {
	text: Type,
	long_text: FileText,
	choice: CheckSquare,
	dropdown: ChevronsUpDown,
	rating: Star,
	nps: TrendingUp,
	date: Calendar,
	slider: SlidersHorizontal,
	file_upload: Upload,
	// Legacy types
	input: Type,
	textarea: FileText,
	select: ChevronsUpDown,
	radio_group: CheckSquare,
	checkbox_group: CheckSquare,
	switch: CheckSquare,
	date_picker: Calendar,
	combobox: ChevronsUpDown,
	multiple_choice: CheckSquare,
	checkbox: CheckSquare,
	email: Type,
	phone: Type,
	linear_scale: SlidersHorizontal,
};

export const questionTypeLabels: Record<string, string> = {
	text: "Short Text",
	long_text: "Long Text",
	choice: "Choice",
	dropdown: "Dropdown",
	rating: "Rating",
	nps: "NPS",
	date: "Date",
	slider: "Slider",
	file_upload: "File Upload",
	// Legacy types
	input: "Input",
	textarea: "Textarea",
	select: "Select",
	radio_group: "Radio Group",
	checkbox_group: "Checkbox Group",
	switch: "Switch",
	date_picker: "Date Picker",
	combobox: "Combobox",
	multiple_choice: "Multiple Choice",
	checkbox: "Checkboxes",
	email: "Email",
	phone: "Phone",
	linear_scale: "Linear Scale",
};
